destination: _sitePDFStage/
url: "http://localhost:40417"
baseurl: "/pdf"
output: pdf
product: SpotlightEnterprise
print_title: Spotlight Enterprise
print_subtitle: Version 12.0
company_name: Quest Software Inc
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: false
      search: false
